<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/talkutalku-com-ng/image/upload/v1554338162/HNGinternship/53456110_832976943706890_8770711882907516928_n.jpg" alt="Costly Okon">
                        <h6>Costly Okon</h6>
                        <p>Front-end Developer</p>
                        <ul class="list">
                           <li><a href="twitter.com/KDcodes" target=""<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="https://github.com/kedehcostly" target=""<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="talkutalku.com.ng/bug found in timbu.com" target=""<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>My name is Costly Okon, i am a student of Cross River University of Calaba 2/4 i am a software developer (Web Front Ent) am also a member of DSCcalabar chapter</p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | Css | HTML</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
